Switch the scripts to support Silverpeas 6 (and only Silverpeas 6, no more Silverpeas 5)

diff --git a/bin/test-silverpeas-update b/bin/test-silverpeas-update
--- a/bin/test-silverpeas-update
+++ b/bin/test-silverpeas-update
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 
 PATH=$PATH:$WORKSPACE/bin
-test "Z$JAVA_HOME" = "Z" && export JAVA_HOME=/usr/lib/jvm/default-java
+test "Z$JAVA_HOME" = "Z" && export JAVA_HOME=/usr/lib/jvm/java-8-oracle
+test "Z$WORKSPACE" = "Z" && die "WORKSPACE environment variable isn't set!"
 
 WORKING_DIR="$WORKSPACE/test-update"
 repo=http://repository.silverpeas.org/files
@@ -14,9 +15,10 @@ cd "$WORKING_DIR"
 wget $repo/latest-dev
 
 VERSION=`cat latest-dev`
-ARCHIVE=silverpeas-${VERSION}-jboss6.tar.gz
-SILVERPEAS_HOME="$WORKING_DIR/${ARCHIVE%.tar.gz}"
-JBOSS_HOME=$WORKSPACE/jboss-6.1.0.Final
+SILVERPEAS=silverpeas-${VERSION}-wildfly10.zip
+JBOSS=wildfly-10.0.0.Final.zip
+SILVERPEAS_HOME="$WORKING_DIR/${SILVERPEAS%.zip}"
+JBOSS_HOME="$WORKING_DIR/${JBOSS%.zip}"
 customconf=$WORKSPACE/settings/CustomerSettings.xml
 oracledriver=$WORKSPACE/settings/ojdbc6_g.jar
 
@@ -28,37 +30,40 @@ function msg {
 function die {
   msg "$1"
   cd
-  rm -r "$WORKING_DIR"
+  rm -r "$WORKING_DIR" 2>/dev/null
   exit 1
 }
 
 function runtest {
   IFS=':' read -ra RDBMS <<< "$1"
   msg "Update test for ${RDBMS[1]}"
-  cd "$SILVERPEAS_HOME/setup/settings"
-  rm -f config.properties
-  echo "DB_NAME=SilverUpdate" > config.properties
-  echo "DB_USER=silverpeas" >> config.properties
-  echo "DB_PASSWD=silverpeas" >> config.properties
-  echo "DB_SERVERTYPE=${RDBMS[1]}"  >> config.properties
-  echo "DB_SERVER=${RDBMS[0]}" >> config.properties
-  SILVERPEAS_HOME="$WORKING_DIR/${ARCHIVE%.tar.gz}" JBOSS_HOME="$WORKSPACE/jboss-6.1.0.Final" RDBMS="${RDBMS[1]}" buildsilverpeas
+  cd "$SILVERPEAS_HOME"
+  rm -f configuration/config.properties
+  echo "DB_NAME=SilverUpdate" > configuration/config.properties
+  echo "DB_USER=silverpeas" >> configuration/config.properties
+  echo "DB_PASSWD=silverpeas" >> configuration/config.properties
+  echo "DB_SERVERTYPE=${RDBMS[1]}"  >> configuration/config.properties
+  echo "DB_SERVER=${RDBMS[0]}" >> configuration/config.properties
+  SILVERPEAS_HOME="$SILVERPEAS_HOME" JBOSS_HOME="$JBOSS_HOME" bin/silverpeas clean install
   ret=$?
   test $ret -eq 0 || die "Update test for ${RDBMS[1]} failed!"
   msg "Update test for ${RDBMS[1]} done"
 }
 
 cd "$WORKING_DIR"
-msg "Fetching and extraction of the archive ${ARCHIVE}..."
-wget $repo/$ARCHIVE
-test $? -eq 0 || die "Cannot fetch the archive ${ARCHIVE}"
-tar zxvf $ARCHIVE
-test $? -eq 0 || die "Cannot open the archive ${ARCHIVE}"
-msg "... done" 
-cp "$customconf" "$SILVERPEAS_HOME"/setup/settings/
-cp "$oracledriver" "$SILVERPEAS_HOME"/bin/jar
+for archive in "$JBOSS $SILVERPEAS"; do
+  msg "Fetching and extraction of the archive ${archive}..."
+  wget $repo/$archive
+  test $? -eq 0 || die "Cannot fetch the archive ${archive}"
+  unzip $archive
+  test $? -eq 0 || die "Cannot open the archive ${archive}"
+  msg "... done" 
+done
 
-runtest $postgresql:POSTGRES
+cp "$customconf" "$SILVERPEAS_HOME"/configuration/silverpeas/
+cp "$oracledriver" "$SILVERPEAS_HOME"/bin/lib/
+
+runtest $postgresql:POSTGRESQL
 runtest $mssql:MSSQL
 runtest $oracle:ORACLE
 
